services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: sheets
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: your_password
      DB_NAME: sheets
      SPREADSHEET_ID: 1kiJT56NKqrKegFCREj3Inz2FZWfwbwvA5kklL85t3Dc
      API_KEY: AIzaSyDwrDGoJ38-LBr9Ic1SUCdJZtpEeeWVP5U
